name: CI Workflow

on:
  pull_request:
    branches:
      - main  

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install -g markdownlint-cli cspell

      - name: Run Markdown linting
        run: markdownlint '**/*.md' --ignore node_modules

      - name: Run spell check
        run: cspell '**/*.md'